include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-raw-types: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    
  exclude:

# https://dart-lang.github.io/linter/lints/
linter:
  rules:
    - prefer_final_locals