name: feedback
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app.
version: 2.2.1
homepage: https://uekoetter.dev/
repository: https://github.com/ueman/feedback
issue_tracker: https://github.com/ueman/feedback/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: Madera
      fonts:
        - asset: feedback/assets/fonts/madera/Monotype - Madera ExtraBold.otf
          weight: 800
        - asset: feedback/assets/fonts/madera/Monotype - Madera ExtraBold Italic.otf
          style: italic
          weight: 800
        - asset: feedback/assets/fonts/madera/Monotype - Madera Bold.otf
          weight: 700
        - asset: feedback/assets/fonts/madera/Monotype - Madera Bold Italic.otf
          style: italic
          weight: 700
        - asset: feedback/assets/fonts/madera/Monotype - Madera Medium.otf
          weight: 500
        - asset: feedback/assets/fonts/madera/Monotype - Madera Medium.otf
          style: italic
          weight: 500
        - asset: feedback/assets/fonts/madera/Monotype - Madera Regular.otf
          weight: 400
        - asset: feedback/assets/fonts/madera/Monotype - Madera Italic.otf
          style: italic
          weight: 400
        - asset: feedback/assets/fonts/madera/Monotype - Madera Light.otf
          weight: 300
        - asset: feedback/assets/fonts/madera/Monotype - Madera Light Italic.otf
          style: italic
          weight: 300
        - asset: feedback/assets/fonts/madera/Monotype - Madera Thin.otf
          weight: 200
        - asset: feedback/assets/fonts/madera/Monotype - Madera Thin.otf
          style: italic
          weight: 200
        - asset: feedback/assets/fonts/madera/Monotype - Madera UltraLight.otf
          weight: 100
        - asset: feedback/assets/fonts/madera/Monotype - Madera UltraLight Italic.otf
          style: italic
          weight: 100

